config/routes.rb
Imsnew::Application.routes.draw do
  resources :free_ebooks

  resources :abbreviations

 resources :users
 resources :sessions, only: [:new, :create, :destroy]
 match 'signup',  to: 'users#new',            via: 'get'
 match 'signin',  to: 'sessions#new',         via: 'get'
 match 'signout', to: 'sessions#destroy',     via: 'delete'
 get 'tags/:tag', to: 'posts#index', as: :tag
 get 'welcome/:article_type', to: 'welcome#page_data', as: :article_type
 resources :posts
 root to: "welcome#index"

end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  before_save {email.downcase! }
  before_create :create_remember_token
  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i
  validates :email, presence: true, format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }

  validates :password, length: { minimum: 6 }


  def User.new_remember_token
    SecureRandom.urlsafe_base64
  end

  def User.encrypt(token)
    Digest::SHA1.hexdigest(token.to_s)
  end



  private

    def create_remember_token
      self.remember_token = User.encrypt(User.new_remember_token)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper


  private
    # Before filters

    def signed_in_user
      unless signed_in?
        store_location
        redirect_to signin_url, notice: "Please sign in."
      end
    end

    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_url) unless current_user?(@user)
    end
    def admin_user
      if signed_in?    
	redirect_to(root_url) unless current_user.admin?
      else
	redirect_to(root_url)
      end
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      sign_in user
      redirect_back_or root_url
    else
      flash.now[:error] = 'Invalid email/password combination'
      render 'new'
    end
  end

  def destroy
    sign_out
    redirect_to root_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :signed_in_user, only: [:index, :show, :edit, :update]
  before_action :correct_user,   only: [:edit, :update]
  before_action :admin_user,     only: :destroy

  def index
    @users = User.paginate(page: params[:page])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      sign_in @user
      flash[:success] = "Welcome to the Sample App!"
      redirect_to @user
    else
      render 'new'
    end
  end

  def show
    @user = User.find(params[:id])
  end

  def edit

  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      flash[:success] = "Profile updated"
      redirect_to @user
    else
      render 'edit'
    end
  end
  
  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User deleted."
    redirect_to users_url
  end

private

    def user_params
      params.require(:user).permit(:name, :email, :password,
                                   :password_confirmation)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
require 'redcarpet/compat'

module ApplicationHelper
  def markdown(text)
    options = [:hard_wrap, :filter_html, :autolink, :no_intraemphasis, :fenced_code, :gh_blockcode]
    syntax_highlighter(Markdown.new(text, *options).to_html).html_safe
  end

  def syntax_highlighter(html)
    doc = Nokogiri::HTML(html)
    doc.search("//pre[@lang]").each do |pre|
      pre.replace Albino.colorize(pre.text.rstrip, pre[:lang])
    end
    doc.to_s
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def sign_in(user)
    remember_token = User.new_remember_token
    cookies.permanent[:remember_token] = remember_token
    user.update_attribute(:remember_token, User.encrypt(remember_token))
    self.current_user = user
  end
  
  def signed_in?
    !current_user.nil?
  end

  def current_user=(user)
    @current_user = user
  end
  
  def current_user
    remember_token = User.encrypt(cookies[:remember_token])
    @current_user ||= User.find_by(remember_token: remember_token)
  end

  def current_user?(user)
    user == current_user
  end

  def sign_out
    current_user.update_attribute(:remember_token,
                                  User.encrypt(User.new_remember_token))
    cookies.delete(:remember_token)
    self.current_user = nil
  end

  def redirect_back_or(default)
    redirect_to(session[:return_to] || default)
    session.delete(:return_to)
  end

  def store_location
    session[:return_to] = request.url if request.get?
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/_bottom_header.html.erb
<div class="span12">
  <div class="navbar">
    <button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <div class="nav-collapse collapse">
      <div id="header">
        <ul class="nav nav-pills">
		<li><%= link_to raw("Programming <span>languages</span>").html_safe, {controller: "welcome", action: "page_data", article_type: 'Programming' } %></li>
        <li><%= link_to raw("Operating <span>System</span>").html_safe, {controller: "welcome", action: "page_data", article_type: 'operating_system' } %></li>
		<li><%= link_to raw("Database <span>System</span>").html_safe, {controller: "welcome", action: "page_data", article_type: 'Database' } %></li>
		<li><%= link_to raw("Unit <span>Testing</span>").html_safe, {controller: "welcome", action: "page_data", article_type: 'Testing' } %></li>
		<li><%= link_to raw("Contact <span>Desk2Mob</span>").html_safe, '#' %></li>
        </ul>
      </div>
    </div>
    <!--/.nav-collapse -->
  </div>
</div>

app/views/layouts/_footer.html.erb
<div class="footer">
  <p align="center">&copy; BAPS, Milpitas <%= Time.now.year %></p>
</div>

app/views/layouts/_meta.html.erb
<meta charset="utf-8">
<title>BAPS, Milpitas</title>
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta name="description" content="">
<meta name="author" content="">

app/views/layouts/_middle_header.html.erb
<div class="span6">
  <div class="logo">
    <%= link_to raw("<sup>Desk2Mob</sup>"), root_path %>
    <%= raw("<br/><span>Share Your Knowledge &amp; Experience</span>") %>
  </div>
</div>
<%= render 'layouts/ads/middle_header_ads' %>

app/views/layouts/_shim.html.erb
<!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/_stylesheet_javascript.html.erb
<%= stylesheet_link_tag    "application", media: "all" %>
<%= javascript_include_tag "application" %>

app/views/layouts/_top_header.html.erb
<div class="masthead">
  <ul class="nav nav-pills pull-right">
    <li>
      <% if signed_in? %>
          <div class="btn-group pull-right">
            <a class="btn dropdown-toggle" data-toggle="dropdown" href="#">
              <i class="icon-user"></i> <%= current_user.name %>
              <span class="caret"></span>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", current_user %></li>
              <li><%= link_to "Settings", edit_user_path(current_user) %></li>
              <% if signed_in? && current_user.admin? %>
                  <li class="divider"></li>
                  <li><%= link_to "Users", users_path %></li>
              <% end %>
              <li class="divider"></li>
              <li><%= link_to "Sign out", signout_path, method: "delete" %></li>

            </ul>
          </div>
      <% else %>
          <p class="pull-right"><%= link_to "Sign In", signin_url %></p>
      <% end %>
    </li>
  </ul>
  <h3 class="muted"><%= link_to raw("<sup>BAPS, Milpitas</sup>"), root_path %></h3>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>

  <%= include_gon %>

  <%= render 'layouts/meta' %>

  <%= csrf_meta_tag %>

  <%= render 'layouts/stylesheet_javascript' %>

  <%= render 'layouts/shim' %>

</head>
<body>
<div class="container-narrow">

  <%= render 'layouts/top_header' %>

  <hr>

  <% flash.each do |name, msg| %>
      <p><%= content_tag :div, msg, id: "flash_#{name}" %></p>
  <% end %>
  <%= yield %>
  <%= debug(params) if Rails.env.development? %>
  <hr>

  <%= render 'layouts/footer' %>
</div>
</body>
</html>

app/views/layouts/box/_box_bottom_curve.html.erb
<div class="bottomBorder">
  <div class="Curve2"></div>
  <div class="Curve1"></div>
  <div class="Curve0"></div>
</div>

app/views/layouts/box/_box_curve.html.erb
<div>
  <div class="Curve0"></div>
  <div class="Curve1"></div>
  <div class="Curve2"></div>
</div>

app/views/layouts/box/_box_title.html.erb
<div class="Box">
  <div class="Title"><a href="#" target="_blank" title=<%= title %>><%= title %></a></div>
</div>

app/views/layouts/box/_content_box.html.erb
<div class="contentBox">
  <table class="table table-condensed table-hover">
    <% content.collect do |row| %>
        <tr>
          <td><a href="#" target="_blank" title=<%= row %>>&#160;&#160;<%= row %></a></td>
        </tr>
     <% end %>
    <tr>
      <td><a class="btn btn-mini" href="#">View All &raquo;&raquo;</a></td>
    </tr>
  </table>
</div>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/users/_fields.html.erb
<%= render 'shared/error_messages' %>

<%= f.label :name %>
<%= f.text_field :name %>

<%= f.label :email %>
<%= f.text_field :email %>

<%= f.label :password %>
<%= f.password_field :password %>

<%= f.label :password_confirmation, "Confirm Password" %>
<%= f.password_field :password_confirmation %>

app/views/users/_user.html.erb
<li>
  <%= link_to user.name, user %>
  <% if current_user.admin? && !current_user?(user) %>
    | <%= link_to "delete", user, method: :delete,
                                  data: { confirm: "You sure?" } %>
  <% end %>
</li> 

app/views/users/edit.html.erb
<div class="row">
  <div class="span6 offset3">
   <h4>Update your profile</h4>
    <%= form_for(@user) do |f| %>
      <%= render 'fields', f: f %><br/>
      <%= f.submit "Save changes", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/index.html.erb
<h4>All users</h4>

<%= will_paginate %>

<ul class="users">
  <%= render @users %>
</ul>

<%= will_paginate %>

app/views/users/new.html.erb
<div class="row">
  <div class="span6 offset3">
    <h4>Sign up</h4>
    <%= form_for(@user) do |f| %>
      <%= render 'fields', f: f %><br/>
      <%= f.submit "Create my account", class: "btn btn-primary" %>
    <% end %>
    <p>Already have account? <%= link_to "Sign In now!", signin_path %></p>
  </div>
</div>

app/views/users/show.html.erb
<div class="row">
  <div class="span6 offset3">
  <aside class="span4">
    <section>
      <h5>
        <%= @user.name %>
      </h5>
    </section>
    <section>
      <h5>
        <%= @user.email %>
      </h5>
    </section>
  </aside>
</div>
</div>

app/views/welcome/index.html.erb
<% if signed_in? %>
	<div class="row-fluid">
	  <div class="span12">
	    <div class="row-fluid">
		<div class="row-fluid">
		  <div class="span12">
		    <div class="span3">
		      <div class="EachBox">
                <%= render 'layouts/box/box_curve' %>
                <div class="Box">
                  <div class="Title"></div>
                </div>
                <div class="contentBox">

                </div>
                <%= render 'layouts/box/box_bottom_curve' %>
		      </div>
		    </div>
		    <!--/span-->
		    <div class="span6">
		      <div class="EachBox">
		        <%= render 'layouts/box/box_curve' %>
			<div class="Box">
				<div class="Title"></div>
			</div>
			<div class="contentBox">

			</div>
		        <%= render 'layouts/box/box_bottom_curve' %>
		      </div>
		    </div>
		    <!--/span-->
		    <div class="span3">
		      <div class="EachBox">
		        <%= render 'layouts/box/box_curve' %>
                <div class="Box">
                  <div class="Title"></div>
                </div>
                <div class="contentBox">

                </div>
		        <%= render 'layouts/box/box_bottom_curve' %>
		      </div>
		    </div>
		    <!--/span-->
		  </div>
		</div>
		<br/>

		<div class="row-fluid">
		  <div class="span12">
		    <div class="span3">
		      <div class="EachBox">

		      </div>
		    </div>
		    <!--/span-->
		    <div class="span6">
		      <div class="EachBox">

		      </div>
		    </div>
		    <!--/span-->
		    <div class="span3">
		      <div class="EachBox">

		      </div>
		    </div>
		    <!--/span-->
		  </div>
		</div>
	    </div>
	  </div>
	</div>
<% end %>